services:
  app:
    build: .
    container_name: october-app
    restart: unless-stopped
    working_dir: /app
    # On production (Dokploy), we don't want to mount the local folder 
    # as it might overwrite the vendor folder we built in the Dockerfile
    # volumes:
    #   - ./:/app
    environment:
      - WEB_DOCUMENT_ROOT=/app
      - PHP_DISPLAY_ERRORS=1
      - PHP_MEMORY_LIMIT=512M
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - APP_LOCALE=${APP_LOCALE}
      - ACTIVE_THEME=${ACTIVE_THEME}
      - BACKEND_URI=${BACKEND_URI}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - LINK_POLICY=${LINK_POLICY}
      - MAIL_MAILER=${MAIL_MAILER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
    ports:
      - "8087:80"
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: october-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: october
      MYSQL_USER: october
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  mailpit:
    image: axllent/mailpit
    container_name: october-mail
    restart: unless-stopped
    ports:
      - "8027:8025"
      - "1027:1025"

volumes:
  db_data:
